export const records = [
  { slNo: 1, hanzi: "被动", pinyin: "bèi dòng", meaning: "not proactive/passive smoking/she played a passive role in the game" },
  { slNo: 2, hanzi: "报酬", pinyin: "bào chou", meaning: "remuneration/this job pays well/the scheme will overpay some and underpay some" },
  { slNo: 3, hanzi: "(原告) 被告 都已经 表示服罪 了 (表示服罪)", pinyin: "bèi gào (bǐaoshì fúzuì)", meaning: "defendant (to admit guilt)/the plaintiff accused the defendant" },
  { slNo: 4, hanzi: "馋...(馋嘴) (贪吃) (流口水)", pinyin: "běnshi", meaning: "I'm craving for maaza, I'm already drooling/I'm a glutton (voracious)" },
  { slNo: 5, hanzi: "扮演", pinyin: "bàn yǎn", meaning: "She often plays the role of the villian/who wants to play the role of Cinderella" },
  { slNo: 6, hanzi: "报答", pinyin: "bào dá", meaning: "I'll repay your money/she repaid my kindness with love" },
  { slNo: 7, hanzi: "卑鄙", pinyin: "bēi bǐ", meaning: "he is despicable and mean" },
  { slNo: 8, hanzi: "贬低 (吹捧)", pinyin: "biǎn dī (chuī pěng)", meaning: "do not belittle others/she will degrade our family name/you flatter me, praise my accomplishments" },
  { slNo: 9, hanzi: "遍布", pinyin: "biàn bù", meaning: "blue flowers are all over the place in this mountain/skyscrapers are all over in singapore" },
  { slNo: 10, hanzi: "变故", pinyin: "biàn gù", meaning: "perhaps something quite unforeseen has happened" },
  { slNo: 11, hanzi: "标题", pinyin: "biāo tí", meaning: "make the title/heading of this news in red color" },
  { slNo: 12, hanzi: "标本", pinyin: "biāo běn", meaning: "give me a specimen/sample of your blood" },
  { slNo: 13, hanzi: "堵塞 (闭塞/阻塞)", pinyin: "dǔ sè (bì sè/zǔ sè)", meaning: "rice grains clogged up the kitchen water pipes" },
  { slNo: 14, hanzi: "变质 (质变) (腐败/败坏)", pinyin: "biàn zhì", meaning: "the food has rotten/gone waste/its full of corruption/this kingdom is corrupted" },
  { slNo: 15, hanzi: "别致 (不凡/非凡)", pinyin: "bié zhì", meaning: "the structure of this temple is unique and fancy" },
  { slNo: 16, hanzi: "不料 (意料/预料)", pinyin: "bù liào", meaning: "it's an un-anticipated/un-expected event/I already anticipated this" },
  { slNo: 17, hanzi: "别扭", pinyin: "biè niu", meaning: "physical or mental uncomfortable/this shoes are a bit uncomfortable/there's a bit awkwardness between us" },
  { slNo: 18, hanzi: "剥削 (人民)", pinyin: "bō xuē", meaning: "she loves to exploit people/the villagers endured centuries of exploitation" },
  { slNo: 19, hanzi: "表态", pinyin: "biǎo tài", meaning: "tell what you think or feel about something/I express my opinion that I love red/I will fight them" },
  { slNo: 20, hanzi: "表决 (投票)", pinyin: "biǎo jué", meaning: "we all decided by vote for a picnic (we voted her/this year vote was cancelled)" },
  { slNo: 21, hanzi: "濒临", pinyin: "bīn lín", meaning: "The company is on the verge of bankruptcy/The village is on the verge of a beautiful lake" },
  { slNo: 22, hanzi: "拨打", pinyin: "bō dǎ", meaning: "If you need help, please dial this number" },
  { slNo: 23, hanzi: "并列", pinyin: "bìng liè", meaning: "They tied for winners/They stand side by side on the stage" },
  { slNo: 24, hanzi: "不由得 (不禁)", pinyin: "bù yóu de", meaning: "I can not help but think about you" },
  { slNo: 25, hanzi: "不得已 (无奈)", pinyin: "bù dé yǐ", meaning: "They have no choice but to sell their house" },

  { slNo: 26, hanzi: "不堪 (受不了/忍不住)", pinyin: "bù kān", meaning: "unbearable/untolerable/This news or pain is unbearable" },
  { slNo: 27, hanzi: "(对...) 不屑一顾", pinyin: "bù xiè yī gù", meaning: "not worth bothering about/She is not even worth bothering to accept his apology" },
  { slNo: 28, hanzi: "布局 (结构) (农舍)", pinyin: "bù jú", meaning: "layout (structure)/She tried to recall the layout of the farmhouse" },
  { slNo: 29, hanzi: "布置 (安排)", pinyin: "bù zhì", meaning: "she furnished the bedroom with love/she also arranged garden with love" },
  { slNo: 30, hanzi: "布告", pinyin: "bù gào", meaning: "notice/bulletin/They have pasted up a notice on the wall" },
  { slNo: 31, hanzi: "(跟不上 你的) 步伐", pinyin: "bù fá", meaning: "pace/step/I can't keep up with your pace" },
  { slNo: 32, hanzi: "灿烂", pinyin: "càn làn", meaning: "The event was held in glittering/brilliant sunshine/there was a glittering smile on her face" },
  { slNo: 33, hanzi: "裁判 (吹响了哨子)", pinyin: "cái pàn (shào zi)", meaning: "The referee blew her whistle" },
  { slNo: 34, hanzi: "参谋", pinyin: "cān móu", meaning: "Show us your element, let us give you advices" },
  { slNo: 35, hanzi: "操劳 (劳累)", pinyin: "cāo láo", meaning: "She worked hard all her life" },
  { slNo: 36, hanzi: "采购 (购买)", pinyin: "cǎi gòu", meaning: "We have to buy more raw materials/She is responsibile for buying  company's daily supplies" },
  { slNo: 37, hanzi: "测量 (胸部)", pinyin: "cè liáng", meaning: "I can't measure her chest" },
  { slNo: 38, hanzi: "阐述 (解释/说明)", pinyin: "chǎn shù", meaning: "She elaborated her viewpoint at the meeting" },
  { slNo: 39, hanzi: "草率 (马虎/含糊) (认真)", pinyin: "cǎo shuài ", meaning: "How can I be careless here while deploying?" },
  { slNo: 40, hanzi: "策划 (谋划)", pinyin: "cè huà", meaning: "to plot (conspiracy)/What are they plotting/scheming secretly/What are you conspiring together?" },
  { slNo: 41, hanzi: "搀扶", pinyin: "chān fú", meaning: "to lend an arm to support sb/She helped the elderly person cross the street" },
  { slNo: 42, hanzi: "缠绕 (藤蔓)", pinyin: "chán rào (téng màn)", meaning: "to entangle/wind around (vines)/Snake wrapped around a tree branch" },
  { slNo: 43, hanzi: "操纵 (操纵杆)", pinyin: "cāo zòng", meaning: "She knows how to manipulate my heart (joystick)" },
  { slNo: 44, hanzi: "层出不穷", pinyin: "céng chū bù qióng", meaning: "Problems keeps arising endlessly" },
  { slNo: 45, hanzi: "查获 (罪犯)", pinyin: "chá huò", meaning: "The police tracked down and seized the criminals and guns (criminal)" },
  { slNo: 46, hanzi: "策略", pinyin: "cè lüè", meaning: "I love your strategy" },
  { slNo: 47, hanzi: "繁荣昌盛 (祖国) (和谐/和睦)", pinyin: "chāng shèng", meaning: "Wish my motherland be flourishing/prosperous and harmony" },
  { slNo: 48, hanzi: "沉思 (思考/考虑)", pinyin: "chén sī", meaning: "Sit there and think/ponder over how to win" },
  { slNo: 49, hanzi: "(提倡) 倡导 (倡议/建议)", pinyin: "chàng dǎo", meaning: "(He has always advocated for peace and friendship) (They proposed establishing a new working group)" },
  { slNo: 50, hanzi: "沉淀 (液体) (沙子)", pinyin: "chén diàn", meaning: "Wait for the sand in this liquid to precipitate" },

  { slNo: 51, hanzi: "陈旧 (破旧)", pinyin: "chén jiù", meaning: "(All her clothes are old-fashioned) (There is an old shabby hut)" },
  { slNo: 52, hanzi: "巢穴 (贼巢/鸟巢/蜂巢/蚁巢)", pinyin: "cháo xué", meaning: "(Its a drogon's nest) (We found the lair of the robbers) (bird nest/bee hive/ ant nest)" },
  { slNo: 53, hanzi: "沉重 (感/打击) (税收)", pinyin: "chén zhòng", meaning: "I am feeling heaviness/This hurt him hard/We have to bear a heavy load of tax (tax)" },
  { slNo: 54, hanzi: "场所 (佛教)", pinyin: "chǎng suǒ", meaning: "In most workplaces smoking is not allowed/Li Yue is a Budhhist site" },
  { slNo: 55, hanzi: "沉着 (惊慌/慌张)", pinyin: "chǎng suǒ", meaning: "He is calm and collected and never nervous, never panics" },
  { slNo: 56, hanzi: "场面", pinyin: "chǎng miàn", meaning: "I can't forget the fighting scene of Wu Xing Shan anime" },
  { slNo: 57, hanzi: "畅销 (书/品)", pinyin: "chàng xiāo", meaning: "sell well (best seller)/Your book will sell well in this summer" },
  { slNo: 58, hanzi: "沉闷 (书/品)", pinyin: "chén mèn", meaning: "(dull/depressed/cloudy) flowers can bring a dull room back to life" },
  { slNo: 59, hanzi: "场合 (正装)", pinyin: "chǎng hé", meaning: "This occasion is very formal, we need to wear formal attire" },
  { slNo: 60, hanzi: "畅通", pinyin: "chàng tōng", meaning: "The roads are clear now/My work is smooth today" },
  { slNo: 61, hanzi: "敞开 (心扉)", pinyin: "chǎng kāi", meaning: "to open wide/She opened the door and window wide/Go do with an open heart (open heart)" },
  { slNo: 62, hanzi: "承包 (承办)", pinyin: "chéng bāo", meaning: "(contract/undertake) Our company has contracted all their projects/She undertook our marriage" },
  { slNo: 63, hanzi: "诚恳 (诚挚)", pinyin: "chéng kěn", meaning: "Lao Han is sincere and earnest" },
  { slNo: 64, hanzi: "成心 (故意)", pinyin: "chéng xīn", meaning: "I'm sorry I didn't do it on purpose" },
  { slNo: 65, hanzi: "称心如意", pinyin: "chèn xīn rú yì", meaning: "(everything one could wish for) This is a job we could wish for/Life is not a bed of roses" },
  { slNo: 66, hanzi: "吃苦 (受苦)", pinyin: "chī kǔ", meaning: "(to bear hardships) (suffer hardship) If other people can endure hardship, why can't I?" },
  { slNo: 67, hanzi: "陈述", pinyin: "chén shù", meaning: "(to state/statement) I stated my viewpoint/Her statement was kept a secret" },
  { slNo: 68, hanzi: "呈现", pinyin: "chéng xiàn", meaning: "(This painting/movie presents a beautiful landscape/story) (The data presented in the report is wrong)" },
  { slNo: 69, hanzi: "成员 (家庭) (队员)", pinyin: "chéng yuán", meaning: "(member) You have already become our family member/group member (team member)" },
  { slNo: 70, hanzi: "澄清 (清澈)", pinyin: "chèng qīng (qīng chè)", meaning: "(clear/to make clear) Clear water/GGS If someone asks please help me clarify" },
  { slNo: 71, hanzi: "(开花) 盛开", pinyin: "shèng kāi", meaning: "(to bloom)(to be in full bloom) The flowers here are in full bloom" },
  { slNo: 72, hanzi: "陈列 (台/室)", pinyin: "chén liè", meaning: "(to display/exhibit) There are many rare treasures exhibited in the museum" },
  { slNo: 73, hanzi: "筹备", pinyin: "chóu bèi", meaning: "(preparations/get ready for sth) Ishigami clan started preparing for the winter/She helped me prepare for my sister's birthday" },
  { slNo: 74, hanzi: "持久 (战/性/力)", pinyin: "chí jiǔ", meaning: "(long lasting/edurance) After a prolonged war he came back/Xiao Long's durability and stamina is unbeatable" },
  { slNo: 75, hanzi: "迟缓 (迟钝) (灵活)", pinyin: "chí huǎn (迟钝)", meaning: "(sluggish/slow in reaction) Suddenly I became sluggish and she became more nimble/flexible" },
]